#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorB,          feedingMotorDos, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeftMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorB,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     backLeftMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     backRightMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     frontRightMotor, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     motorD,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    goalGrabber,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float pie = 3.14159;
float track = 17.0;
float halfTrack = track / 2.0;
float wheelDiam = 3.88;
float robotCircum=track*3.14;
float wheelRadius = wheelDiam / 2.0;
float wheelCircumference = wheelDiam * PI;
float ticksPerInches = 2160 / wheelCircumference;
float ticksPerInchesNeveRest=1680/wheelCircumference;
float halfRobotCircumference = track*pie;
float robotCircumference = track*2*pie;
float j = 0;
void moveBackward(float feet, float motorSpeed)
{
	nMotorEncoder[backLeftMotor] = 0;
	float inches= (feet * 12.0) - 1.0;
	//inches-=4;
	float nTicks=inches*ticksPerInchesNeveRest;
	//nTicks -= nTicks * calcPercentErrorMoveForward(feet);
	//nTicks-=nTicks*0.295;
	writeDebugStreamLine("ticks: %d", nTicks);
	while(abs(nMotorEncoder[backLeftMotor]) < nTicks)
	{

		motor[frontRightMotor] = motorSpeed;
		motor[frontLeftMotor] = motorSpeed;
		motor[backRightMotor] = -motorSpeed;
		motor[backLeftMotor] = motorSpeed;
		writeDebugStreamLine("ticks: %d", nMotorEncoder[backLeftMotor]);
	}
	motor[frontLeftMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[backRightMotor] = 0;
	motor[backLeftMotor] = 0;
}
void moveFoward(float feet, float motorSpeed)
{
	nMotorEncoder[backLeftMotor] = 0;
	float inches= (feet * 12.0) - 1.0;
	//inches-=4;
	float nTicks=inches*ticksPerInchesNeveRest;
	//nTicks -= nTicks * calcPercentErrorMoveForward(feet);
	//nTicks-=nTicks*0.295;
	writeDebugStreamLine("ticks: %d", nTicks);
	while(abs(nMotorEncoder[backLeftMotor]) < nTicks)
	{

		motor[frontRightMotor] = -motorSpeed;
		motor[frontLeftMotor] = -motorSpeed;
		motor[backRightMotor] = motorSpeed;
		motor[backLeftMotor] = -motorSpeed;
		writeDebugStreamLine("ticks: %d", nMotorEncoder[backLeftMotor]);
	}

	motor[frontLeftMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[backRightMotor] = 0;
	motor[backLeftMotor] = 0;

}

void rightTwoWheelTurn(float degreesMoved, float motorSpeed)
{
	nMotorEncoder[backLeftMotor] = 0;
	float nTicks = abs((degreesMoved*halfTrack)/(wheelRadius));
	//nticks= nticks* 1.3 * 5/ 9;
	while(abs(nMotorEncoder[backLeftMotor]) < nTicks*5)
	{
		motor[frontRightMotor] = motorSpeed;
		motor[frontLeftMotor] = -motorSpeed;
		motor[backRightMotor] = -motorSpeed;
		motor[backLeftMotor] = -motorSpeed;
	}
}
void leftTwoWheelTurn(float degreesMoved, float motorSpeed)
{
	nMotorEncoder[backLeftMotor] = 0;
	float nTicks = abs((degreesMoved*halfTrack)/(wheelRadius));
	//nticks= nticks* 1.3 * 5/ 9;
	while(abs(nMotorEncoder[backLeftMotor]) < nTicks*5)
	{
		motor[frontRightMotor] =- motorSpeed;
		motor[frontLeftMotor] = motorSpeed;
		motor[backRightMotor] = motorSpeed;
		motor[backLeftMotor] = motorSpeed;
	}
}
void leftOneWheelTurn(float degreesMoved, float motorSpeed)
{
	nMotorEncoder[backRightMotor] = 0;
	float totalTicks= robotCircum * ticksPerInchesNeveRest;
	float percentCircum = degreesMoved/360;
	//float nInches = percentCircum * robotCircum;
	float nTicks = abs(totalTicks*percentCircum);
	//nticks= nticks* 1.3 * 5/ 9;
	writeDebugStreamLine("%d",nMotorEncoder[backRightMotor] );
	while(abs(nMotorEncoder[backRightMotor]) < nTicks*2)
	{
		motor[frontRightMotor] = -motorSpeed;
		//motor[frontLeftMotor] = -motorSpeed;
		motor[backRightMotor] = motorSpeed;
		//motor[backLeftMotor] = -motorSpeed;
	}
}
void knockPole (int position){//position 1,2,or 3
	if(position==3){
		int nfeet=47.0/12.0;
		moveFoward(nfeet, 100);
		wait1Msec(1.0);
		rightTwoWheelTurn(85, 100);
		wait1Msec(0.5);
		nfeet=20.0/12.0;
		moveFoward(nfeet, 100);
		wait1Msec(0.5);
		rightTwoWheelTurn(45.0,75.0);
		/*wait1Msec(0.5);
		moveForward(2.0/12.0, 100);
		/*wait1Msec(.5);
		moveFoward(2, 75);
		wait1Msec(0.5);
		leftTwoWheelTurn(9.0, 75);
		wait1Msec(.5);
		moveFoward(.68, 125);
		wait1Msec(.5);
		leftTwoWheelTurn(58.0, 80);
		wait1Msec(.5);
		moveFoward(.9, 125);*/
		}else if(position ==2){
		moveFoward(22.0/12.0, 75);
		//moveFoward(0,0);
		wait1Msec(1);
		rightTwoWheelTurn(62.5, 85);
		wait1Msec(1);
		moveFoward(32.0/12.0, 150);
		wait1Msec(0.5);
		rightTwoWheelTurn(45.0, 75.0);
		}else if(position ==1 ){
		moveFoward(18.0/12.0, 75);
		wait1Msec(1);
		rightTwoWheelTurn(90.0, 85);
		wait1Msec(0.5);
		moveFoward(36.0/12.0, 50);
		wait1Msec(2.0);
		leftTwoWheelTurn(37.5, 75);
		wait1Msec(0.5);
		moveFoward(14.0/12.0, 50);
		wait1Msec(0.5);
		rightTwoWheelTurn(45.0, 50);
	}
}

void driveDownRamp(){
	servo(goalGrabber)=180;
	moveFoward(7.5,75);
}

void grabGoalsNoRobot(){
	wait10Msec(1.0);
	moveFoward(0.0,0.0);
	//wait10Msec(5.0);
	//leftTwoWheelTurn(160.0, 25);
	//wait10Msec(5.0);
	//moveFoward(1.0,25.0);
	wait10Msec(5.0);
	leftOneWheelTurn(156, 50);
	wait10Msec(5.0);
	moveBackward(1.20,75);
	wait10Msec(1.0);
	servo(goalGrabber) = 3;
	wait10Msec(75.0);
	moveFoward(1.4, 75);
	wait10Msec(1.0);
	leftOneWheelTurn(65, 75);
	wait10Msec(1.0);
	moveFoward(7.2, 75);
	wait10Msec(1.0);
	moveBackward(2.0, 75);
	wait10Msec(1.0);
	leftOneWheelTurn(146, 75);
	wait10Msec(1.0);
	moveBackward(2.6, 75);
}
//void grabGoalsWithRobot(){
	/*wait10Msec(1.0);
	leftTwoWheelTurn(90, 75);
	wait10Msec(1.0);
	moveFoward(1.2, 75);
	wait10Msec(1.0);
	rightTwoWheelTurn(90,75);
	wait10Msec(1.0);
	moveFoward(2.5);
	wait10Msec(1.0);
	leftOneWheelTurn(90, 100);
	wait10Msec(1.0);
	moveBackward(1.0, 75);
	servo(goalGrabber) = 3;
	*/
	//moveFoward(3.4, 75);




//void grabGoals(){
	//if(SensorValue[ultrasonicSensor] <=40){
	//	grabGoalsWithRobot();
	//}

	//else{
		//grabGoalsNoRobot();
   //}
//}





	//moveFoward(6.5,75.0);
	//wait10Msec(5.0);
	//leftTwoWheelTurn(45.0, 25);
//}
/*wait10Msec(5.0);
moveFoward(3.0,75);
wait10Msec(1.0);
moveFoward(0.0,0.0);
wait10Msec(1.0);
leftTwoWheelTurn(45.0, 50);
wait10Msec(5.0);
moveFoward(1.0,25.0);
wait10Msec;
wait10Msec(1.0);
moveFoward(1.0, 50);
}
*/
void grabGoalsWithRobot(){
  servo(goalGrabber)=128;
	moveFoward(3, 75);
	wait10Msec(2.0);

	leftTwoWheelTurn(40, 75);
	wait10Msec(2.0);
	moveFoward(2.8,75);
	wait10Msec(2.0);
	moveFoward(0,0);
	wait10Msec(2.0);
	rightTwoWheelTurn(80, 75);
	wait10Msec(2.0);
	moveFoward(4.5,75);
	wait10Msec(2.0);
	leftOneWheelTurn(225, 75);
	wait10Msec(2.0);
	leftOneWheelTurn(95, -75);
	wait10Msec(2.0);
	moveBackward(1.75, 75);
	wait10Msec(2.0);
	servo(goalGrabber)=0;
	wait10Msec(75);
	//moveFoward(0,0);
	//wait10Msec(5.0);

}
//task main(){
	//grabGoalsWithRobot();
	//servo(goalGrabber)=128;
	//wait10Msec(5.0);
	//servo(goalGrabber)=0;
	//wait10Msec(5.0);
	/*moveFoward(3, 75);
	wait10Msec(2.0);

	leftTwoWheelTurn(40, 75);
	wait10Msec(2.0);
	moveFoward(2,75);
	wait10Msec(2.0);
	moveFoward(0,0);
	wait10Msec(2.0);
	rightTwoWheelTurn(75, 75);
	wait10Msec(2.0);
	moveFoward(5.2,75);
	wait10Msec(2.0);
	moveFoward(0,0);
	wait10Msec(2.0);*/
//}
//}
